name = "babygrade-site"
compatibility_date = "2026-05-09"
compatibility_flags = ["global_fetch_strictly_public"]

routes = [
  { pattern = "babygrade.kr", custom_domain = true },
  { pattern = "www.babygrade.kr", custom_domain = true }
]

[assets]
directory = "./dist"
